# Generated by Django 5.2.4 on 2026-05-12 17:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verb', models.CharField(choices=[('reviewed', 'Reviewed'), ('logged', 'Logged'), ('liked', 'Liked'), ('followed', 'Followed'), ('listed', 'Listed')], max_length=20)),
                ('object_type', models.CharField(max_length=20)),
                ('object_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity_activity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity_list',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'activity_listgame',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('playing', 'Playing'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('want_to_play', 'Want to Play')], max_length=20)),
                ('played_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity_log',
            },
        ),
    ]
