# Generated by Django 5.2.4 on 2026-05-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
